# Generated by Django 5.2.8 on 2025-11-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Боеприпасы универсальные', max_length=100)),
                ('quantity', models.PositiveBigIntegerField(default=400000, verbose_name='Общий остаток')),
                ('monthly_incoming', models.PositiveIntegerField(default=200000, help_text='Поступает в месяц')),
                ('monthly_outgoing', models.PositiveIntegerField(default=350000, help_text='Расход в месяц')),
                ('critical_threshold', models.PositiveIntegerField(default=100000, help_text='Критический минимум')),
            ],
            options={
                'verbose_name': 'Боеприпасы',
                'verbose_name_plural': 'Боеприпасы',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ШВ', 'Штурмовые винтовки'), ('ПП', 'Пистолеты-пулемёты'), ('РП', 'Ручные пулемёты'), ('СВ', 'Снайперские винтовки')], max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория оружия',
                'verbose_name_plural': 'Категории оружия',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('critical_threshold', models.PositiveIntegerField(default=5000, help_text='При каком остатке слать тревогу')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.weaponcategory')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружие',
            },
        ),
    ]
